name: CI

on:
  push:
    branches: [ master ]

  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    container: 
      image: fmcore/flagbrew_compiler
      credentials:
        username: ${{ secrets.DHU }}
        password: ${{ secrets.DHA }}

    steps:
      - name: "Clone"
        run: git clone --recurse-submodules -j8 https://github.com/FlagBrew/PKSM.git
      - name: "Build"
        working-directory: "./PKSM"
        run: |
          make
          zip -r PKSM.zip 3ds/out/PKSM.cia 3ds/out/PKSM.3dsx 3ds/out/PKSM.elf
      - name: "Push"
        working-directory: "./PKSM"
        run: "curl -F 'cia=@3ds/out/PKSM.cia' -F 'zip=@PKSM.zip' -F '3dsx=@3ds/out/PKSM.3dsx' --header 'secret: ${{ secrets.GHU }}' --header 'extensions: cia,zip,3dsx' --header 'app: PKSM' --header 'hash: ${{ github.sha }}' ${{ secrets.PURL }}"
